apiVersion: v1
kind: Service
metadata:
  name: big-agi-service
  namespace: argocd
spec:
  selector:
    app: big-agi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-agi
  namespace: argocd
  labels:
    app: big-agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-agi
  template:
    metadata:
      labels:
        app: big-agi
    spec:
      containers:
        - name: big-agi
          image: ghcr.io/enricoros/big-agi:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          command: ["next", "start", "-p", "3000"]