apiVersion: v1
kind: Service
metadata:
  name: transfersh-service
  namespace: default
spec:
  selector:
    app: transfersh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-app
  namespace: default
  labels:
    app: transfersh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfersh
  template:
    metadata:
      labels:
        app: transfersh
    spec:
      containers:
        - name: transfer-container
          image: dutchcoders/transfer.sh:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
#          env:
#            - name: AWS_REGION
#              value: "us-east-1"
#            - name: AWS_S3_BUCKET
#              value: "transfer-sh"
#            - name: AWS_ACCESS_KEY_ID
#              valueFrom:
#                secretKeyRef:
#                  name: aws-credentials
#                  key: aws_access_key_id
#            - name: AWS_SECRET_ACCESS_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: aws-credentials
#                  key: aws_secret_access_key